jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello world"
  optional_job:
    docker:
      - image: circleci/node
    
    steps:
      - checkout
      - run: echo "optional_job"      
  test:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run: echo "test job"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build: 
          filters:
            tags:
              only:
                - /.*/  
      - optional_job:
          filters:
            tags:
              only:
                - /^qa-.*/
            branches:
              ignore:
                - /.*/                     
      - test:
          requires:
            - build
            - optional_job
         

            
          


