jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello world"
      - run: git clone https://github.com/HennaAbbas/test_working_dir
  test:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run: echo "test job"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
     
      - test:
          requires:
            - build

            
          


