jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello world"
  test:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run: echo "test job"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
          filters:
            tags:
              only:
                - /.*/      
      - test:
          requires:
            - build
            
          


